const GLOBAL_VARS = {
   linkedInUrl: "https://www.linkedin.com/in/leonardo-20-as/",
   lattesUrl: "https://lattes.cnpq.br/2911002601216607"
};

// Objeto com traduções
const translations = {
  en: {
    home: "Home",
    about: "About",
    education: "Education",
    experience: "Experience",
    projects: "Projects",
    contact: "Contact",
    hero_subtitle: "Electrical Engineer | Data Scientist | Software Developer",
    contact_button: "Get in Touch",
    about_title: "About Me",
    about_text:
      "I am Leonardo Santos, an electrical engineer with expertise in electrical projects, integrated circuit design, firmware, and software development. I work with digital signal processing, FPGA, and precision agriculture, using Python, C, C++, Java, JavaScript, AWS, and more.",
    education_title: "Academic Background",
    education_ufpr: "Electrical Engineering - UFPR, Curitiba, PR",
    education_gics: "Scientific Researcher - GICS, Curitiba, PR",
    education_internship: "Engineering Intern - Curitiba, PR",
    education_baja: "Extension Project - Baja SAE, UFPR",
    education_PET: "Extension Project - PET, UFPR",
    experience_title: "Professional Experience",
    experience_iotag: "Software Developer - IOTAG, Curitiba, PR",
    projects_title: "Projects",
    project_assistant: "Multimodal Virtual Assistant",
    project_lock: "Smart Electronic Lock",
    project_trng: "TRNG Integrated Circuit",
    project_fake_news: "Fake News Detector",
    projects_invite:
      'Want to know more about my projects? Visit my <a href="' + GLOBAL_VARS.LinkedinUrl + '" class="text-blue-400 hover:underline">LinkedIn</a> and <a href="' + GLOBAL_VARS.LattesUrl + '" class="text-blue-400 hover:underline">Lattes</a>!',
    skills_title: "Technical Skills",
    skills_programming: "Programming Languages",
    skills_programming_list: "Python, C, C++, Java, JavaScript, HTML/CSS",
    skills_circuits: "Circuit Design",
    skills_circuits_list: "Cadence, ADS, Altium Designer, Proteus",
    skills_3d: "3D Modeling",
    skills_3d_list: "SolidWorks, Fusion 360, Catia",
    skills_frameworks: "Frameworks",
    skills_frameworks_list: "OpenCV, FastAPI, LangChain",
    skills_databases: "Databases",
    skills_databases_list: "SQL, AWS integration",
    skills_others: "Others",
    skills_others_list:
      "Web development, circuit simulation, communication, time management",
    contact_title: "Connect with Me",
    contact_lattes: "Lattes Profile",
    contact_linkedin: "LinkedIn Profile",
    contact_phone: "Phone: (41) 98826-7727",
    footer: "© 2025 Leonardo Santos. All rights reserved.",
    curriculo_pt: "Resume in Portuguese",
    curriculo_en: "Resume in English",
    curriculo_es: "Resume in Spanish",
    nav_home: "Home",
    nav_about: "About",
    nav_education: "Education",
    nav_experience: "Experience",
    nav_projects: "Projects",
    nav_contact: "Contact",
    portifolio_title: "Resume of Leonardo Santos",
  },
  pt: {
    home: "Home",
    about: "Sobre",
    education: "Formação",
    experience: "Experiência",
    projects: "Projetos",
    contact: "Contato",
    hero_subtitle:
      "Engenheiro Eletricista | Cientista de Dados | Desenvolvedor de Software",
    contact_button: "Entre em Contato",
    about_title: "Sobre Mim",
    about_text:
      "Sou Leonardo Santos, engenheiro eletricista com expertise em projetos elétricos, design de circuitos integrados, firmware e desenvolvimento de software. Trabalho com processamento de sinais digitais, FPGA, e agricultura de precisão, utilizando Python, C, C++, Java, JavaScript, AWS e mais.",
    education_title: "Formação Acadêmica",
    education_ufpr: "Engenharia Elétrica - UFPR, Curitiba, PR",
    education_gics: "Pesquisador Científico - GICS, Curitiba, PR",
    education_internship: "Estagiário de Engenharia - Curitiba, PR",
    education_baja: "Projeto de Extensão - Baja SAE, UFPR",
    education_PET: "Projeto de Extensão Tutorial - PET, UFPR",
    experience_title: "Experiência Profissional",
    experience_iotag: "Desenvolvedor de Software - IOTAG, Curitiba, PR",
    projects_title: "Projetos",
    project_assistant: "Assistente Virtual Multimodal",
    project_lock: "Fechadura Eletrônica Inteligente",
    project_trng: "Circuito Integrado TRNG",
    project_fake_news: "Detector de Fake News",
    projects_invite:
      "Quer saber mais sobre meus projetos? Visite meu <a href='" +
      GLOBAL_VARS.LinkedinUrl +
      "' class='text-blue-400 hover:underline'>LinkedIn</a> e <a href='" +
      GLOBAL_VARS.LattesUrl +
      "' class='text-blue-400 hover:underline'>Lattes</a>!",
    skills_title: "Habilidades Técnicas",
    skills_programming: "Linguagens de Programação",
    skills_programming_list: "Python, C, C++, Java, JavaScript, HTML/CSS",
    skills_circuits: "Design de Circuitos",
    skills_circuits_list: "Cadence, ADS, Altium Designer, Proteus",
    skills_3d: "Modelagem 3D",
    skills_3d_list: "SolidWorks, Fusion 360, Catia",
    skills_frameworks: "Frameworks",
    skills_frameworks_list: "OpenCV, FastAPI, LangChain",
    skills_databases: "Bancos de Dados",
    skills_databases_list: "SQL, integração com AWS",
    skills_others: "Outros",
    skills_others_list:
      "Desenvolvimento web, simulação de circuitos, comunicação, gestão de tempo",
    contact_title: "Conecte-se Comigo",
    contact_lattes: "Perfil Lattes",
    contact_linkedin: "Perfil LinkedIn",
    contact_phone: "Telefone: (41) 98826-7727",
    footer: "© 2025 Leonardo Santos. Todos os direitos reservados.",
    curriculo_pt: "Currículo em Português",
    curriculo_en: "Currículo em Inglês",
    curriculo_es: "Currículo em Espanhol",
    nav_home: "Home",
    nav_about: "Sobre",
    nav_education: "Formação",
    nav_experience: "Experiência",
    nav_projects: "Projetos",
    nav_contact: "Contato",
    portifolio_title: "Portfólio de Leonardo Santos",
  },
  es: {
    home: "Inicio",
    about: "Sobre Mí",
    education: "Formación",
    experience: "Experiencia",
    projects: "Proyectos",
    contact: "Contacto",
    hero_subtitle:
      "Ingeniero Eléctrico | Científico de Datos | Desarrollador de Software",
    contact_button: "Contactar",
    about_title: "Sobre Mí",
    about_text:
      "Soy Leonardo Santos, ingeniero eléctrico con experiencia en proyectos eléctricos, diseño de circuitos integrados, firmware y desarrollo de software. Trabajo con procesamiento de señales digitales, FPGA y agricultura de precisión, utilizando Python, C, C++, Java, JavaScript, AWS y más.",
    education_title: "Formación Académica",
    education_ufpr: "Ingeniería Eléctrica - UFPR, Curitiba, PR",
    education_gics: "Investigador Científico - GICS, Curitiba, PR",
    education_internship: "Pasante de Ingeniería - Curitiba, PR",
    education_baja: "Proyecto de Extensión - Baja SAE, UFPR",
    education_PET: "Proyecto de Extensión Tutorial - PET, UFPR",
    experience_title: "Experiencia Profesional",
    experience_iotag: "Desarrollador de Software - IOTAG, Curitiba, PR",
    projects_title: "Proyectos",
    project_assistant: "Asistente Virtual Multimodal",
    project_lock: "Cerradura Electrónica Inteligente",
    project_trng: "Circuito Integrado TRNG",
    project_fake_news: "Detector de Noticias Falsas",
    projects_invite:
      "¿Quieres saber más sobre mis proyectos? ¡Visita mi <a href='" +
      GLOBAL_VARS.LinkedinUrl +
      "' class='text-blue-400 hover:underline'>LinkedIn</a> y <a href='" +
      GLOBAL_VARS.LattesUrl +
      "' class='text-blue-400 hover:underline'>Lattes</a>!",
    skills_title: "Habilidades Técnicas",
    skills_programming: "Lenguajes de Programación",
    skills_programming_list: "Python, C, C++, Java, JavaScript, HTML/CSS",
    skills_circuits: "Diseño de Circuitos",
    skills_circuits_list: "Cadence, ADS, Altium Designer, Proteus",
    skills_3d: "Modelado 3D",
    skills_3d_list: "SolidWorks, Fusion 360, Catia",
    skills_frameworks: "Frameworks",
    skills_frameworks_list: "OpenCV, FastAPI, LangChain",
    skills_databases: "Bases de Datos",
    skills_databases_list: "SQL, integración con AWS",
    skills_others: "Otros",
    skills_others_list:
      "Desarrollo web, simulación de circuitos, comunicación, gestión del tiempo",
    contact_title: "Conéctate Conmigo",
    contact_lattes: "Perfil Lattes",
    contact_linkedin: "Perfil LinkedIn",
    contact_phone: "Teléfono: (41) 98826-7727",
    footer: "© 2025 Leonardo Santos. Todos los derechos reservados.",
    curriculo_pt: "Currículo en Portugués",
    curriculo_en: "Currículo en Inglés",
    curriculo_es: "Currículo en Español",
    nav_home: "Inicio",
    nav_about: "Sobre Mí",
    nav_education: "Formación",
    nav_experience: "Experiencia",
    nav_projects: "Proyectos",
    nav_contact: "Contacto",
    portifolio_title: "Currículo de Leonardo Santos",
  },
};